### ISSUE TITLE
Device Back up script error: UnicodeEncodeError: 'ascii' codec can't encode character u'\u2019' in position 1640: ordinal not in range(128)

### ISSUE THREAD

**Issue by L4stPL4Y3R** [PacktPublishing/Hands-On-Enterprise-Automation-with-Python#1]
Hello,
I am getting error while execute device backup script.
The concern is first two device or 1 device getting proper output but after that I am getting this error.
`[root@device_backup]# python backup.py
2018-08-06 15:36:38.806536 Connecting to device 172.16.145.121
2018-08-06 15:36:51.616336 Saving config from device 172.16.145.121
Traceback (most recent call last):
  File "backup.py", line 33, in <module>
    f.write(running_config)
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2019' in position 1640: ordinal not in range(128) `

Please help me out to resolve this issue.
Thank you in Advance.

**Comment by gaurav-packt** [comment]
If the issue still exists kindly reopen the issue.
